name: Build Docker Image (Release)

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v1
        with:
          push: false
          repository: recognizer-intermediate-artifacts
          tags: latest
          
      - uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: recognizer-intermediate-artifacts:latest
          path: /build/recognizer/build/dist/.

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{ steps.extract.outputs.destination }}/*

      # - name: Upload Dist
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: ${{ steps.extract.outputs.destination }}
      #     name: penguin-recognizer-wasm
